### ISSUE TITLE
Use `Symbol.hasInstance` to fix `instanceOf` operator

### ISSUE THREAD

**Issue by FredyC** [stampit-org/stamp-specification#114]
Based on discussion in https://github.com/stampit-org/stampit/issues/312.

[Specification](https://tc39.github.io/ecma262/#sec-function.prototype-@@hasinstance)
[MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/hasInstance)
[Dr. Axel Rauschmayer](http://2ality.com/2015/09/well-known-symbols-es6.html#symbolhasinstance-method)

Apparently, the Symbol.hasInstance can be used for a function too. That could be useful to actually check if stamp is composed of some other stamp by using `instanceOf`

Support is [not that terrible](http://kangax.github.io/compat-table/es6/#test-well-known_symbols_Symbol.hasInstance_a_href=_https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/hasInstance_title=_MDN_documentation_img_src=_../mdn.png_alt=_MDN_(Mozilla_Development_Network)_logo_width=_15_height=_13_/_/a_nbsp;
). A question is what happens if used in an environment without support. It would break the code and it would be really hard to track such issues.

**Comment by koresar** [comment]
That's great proposal!

It would help some Java-minded people at least.

Although, it might benefit only minority of stamp users. Like, 1%. :)
Also, it deoptimizes V8: ["Install Symbol.hasInstance property anywhere disables fast-path globally for the VM"](https://stackoverflow.com/a/1919670/188475).
And there can be other performance implications, like memory. So, we should make this feature optional.

We should accept the "composers proposal" - #109. It's a powerful universal solution which would give multiple abilities. To name a few:
* `instanceof` implementation (see example [here](https://github.com/stampit-org/stampit/issues/312#issuecomment-303299461))
* Collision checks - https://www.npmjs.com/package/@stamp/collision
* `Stamp.constructor` - [fp-constructor](https://www.npmjs.com/package/@stamp/fp-constructor) (asked by Eric Elliott)
* Property privatization implementation via proxy prototype - [Privatize](https://www.npmjs.com/package/@stamp/privatize). This one is getting popular.
* Arbitrary `MyStamp.name` - [Named](https://github.com/stampit-org/stamp/tree/named/packages/named) stamp. (It's currently can be only "Stamp", nothing else)
* etc etc etc

This means that if someone want a feature like `instanceof` - he can simply compose it into the base stampit. 
Untested code of `./stampit.js` or something:
```js
import _stampit from 'stampit';
import InstanceOfStamp from `@stamp/instanceof`;
export default _stampit.bind(undefined, InstanceOfStamp);
```
We can even add a simple API to `stampit`. Something like: `stampit.extendBaseStamp(...composables)`.
So that if anyone would need `instanceof` in the entire application then just `stampit.extendBaseStamp(require('@stamp/instanceof'))` on the app startup. And done!

=====

Wrap up.
**Proposed change is a performance killer. Let's make it optional using the composers #109 feature.**

**Comment by FredyC** [comment]
> We can even add a simple API to `stampit`. Something like: `stampit.extendBaseStamp(...composables)`.
> So that if anyone would need `instanceof` in the entire application then just `stampit.extendBaseStamp(require('@stamp/instanceof'))` on the app startup. And done!

I certainly like this idea, it might actually work like babel or eslint presets and just go like `stampit.inject('instanceof')` which would do `require` in behind.

Anyway you are right that adding this to spec for everyone is probably not a good idea.

**Comment by koresar** [comment]
I'd like to remind that `instanceof` would rely on the `composers` feature. Which is experimentally implemented atm in the "stampit" module.

**Comment by FredyC** [comment]
@koresar What about reminding that in a relevant issue? :) Maybe even create PR that would update the spec. I still haven't used composers for anything, so it's rather alien to me.

**Comment by koresar** [comment]
Thanks for the reminder.

If you used the `Privatize` then you used composers. :)
