### ISSUE TITLE
stamp.compose.configuration - what's that?

### ISSUE THREAD

**Issue by koresar** [stampit-org/stamp-specification#5]
@ericelliott I'm trying to get my head around `configuration`
> configure(options...) => stamp: Creates a new stamp with stamp options. e.g. descriptor presets. Users can use this to implement custom stamp types via initializer.

Could you please elaborate on that? I do not understand the purpose. What that for? Any examples maybe?

**Comment by koresar** [comment]
Hello. Just a reminder that I'd love to hear an answer to this question. /cc @ericelliott

**Comment by ericelliott** [comment]
`configuration` is an extensibility point where users of composables can define their own meta properties that can get merged.

For example, it can store presets (named shortcuts) for `propertyDescriptors`, or it can define the behavior of specialty stamps such as react-stampit.

It is necessary to include it in the composables spec so that its meta-settings can get deep merged during stamp composition.

**Comment by koresar** [comment]
### CODE SAMPLES
please.
When talking about code I prefer code to literature. :)

**Comment by koresar** [comment]
If "configuration" is deeps merged you loose functions. :)
```js
var obj = _.merge({}, { a: function(){} })
console.log(typeof obj.a);
```
will print "object", not "function".

**Comment by koresar** [comment]
So, then how do you see people are using this "configuration"? If it's shallow assigned then people won't be able to mix two configurations from similar stamps.

Also, I don't see people using configuration over statics. Statics is a better place to store configuration things.

**Comment by ericelliott** [comment]
Then we need a special version of deep merge that does not filter functions. For example, in the case of descriptor presets:

```js
stamp.compose.configuration.descriptorPresets = {
  "name": {
    get: function () {
      return `Hi, my name is ${ this.name }`; 
    }
  }
}
```

**Comment by ericelliott** [comment]
It's not shallow assigned. It needs to be deep merged, and it needs to allow functions in order to support presets for propertyDescriptors.

**Comment by koresar** [comment]
If you want functions then they should be assigned. You can't effectilvely clone/deepmerge functions. :)
So, at the end of the day, funcations will be shallow copied. Right?

**Comment by koresar** [comment]
I still think we should remove "configuraiton" form the standard. Because standard must be Stupid Simple (as in KISS). We are already overcomplicating it with the "special version of deep merge"

**Comment by ericelliott** [comment]
If there are two functions with the same name, the last in wins.

Standards should be open for extension. Configuration is a stamp extensibility point. Having a stamp extensibility point simplifies it because it gives users a way to create specialized stamps in a way that is supported by the standard.

The alternative is that specialized stamps and other stamp extensions are handled ad-hoc in different ways by different libraries with no standard for interoperability between stamp types.

For example, the current react-stampit doesn't interoperate completely with existing stamps because there was no extensibility point, and react-stampit had to do its own thing.

**Comment by koresar** [comment]
Okay. That explains the need. Knowing the internals of the `react-stampit` I also understand why statics is not a good place to store configuration.

The last qeustion is not answered yet. How to bloody merge the things? :)))

**Comment by koresar** [comment]
Your proposal to overwrite functions will not deeply merge subproperties of the function.

```js
var conf1 = { func: function() {} };
conf1.func.X = 42;
var conf2 = { func: function() {} };

var conf = mergeConfiguration(conf1, conf2);

assert(conf.func.X, 42); // This will throw, I expect it not to throw.
```

Please, specify the desired behavior.

**Comment by ericelliott** [comment]
> Your proposal to overwrite functions will not deeply merge subproperties of the function.

Good point. Can you think of a good solution?

**Comment by koresar** [comment]
Not yet. I believe we should try to code some examples and then see. For now I'd mark "configuration" as "not yet finalized".

**Comment by ericelliott** [comment]
Using underscore.object.merge for now. I think it's probably good enough.

**Comment by koresar** [comment]
You mean `lodash/object/merge`. Underscore never had a `merge` function. :)

We can close this issue I suppose.
